config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :users
  get 'profile' => 'profiles#show'

  scope "/admin" do
    resources :users, :controller => "users"
  end
  get 'dashboard' => 'admins#dashboard'
  get 'subforums_index' => 'admins#subforums_index'
  get 'users_index' => 'admins#users_index'
  get 'topics_index' => 'admins#topics_index'
  get 'statistics' => 'admins#statistics'
  
  resources :subforums, shallow: true do
  	resources :topics do
  		resources :replies
  	end
  end

end

app/views/admins/dashboard.html.erb
<div class = "dashboard-links group">
	<div class = "dashboard-links-top group">
		<%= link_to "Users", users_index_path, class: "dashboard-users-link" %>
		<%= link_to "Subforums", subforums_index_path, class: "dashboard-subforums-link" %>
	</div>
	<div class = "dashboard-links-bottom group">
		<%= link_to "Topics", topics_index_path, class: "dashboard-topics-link" %>
		<%= link_to "Statistics", statistics_path, class: "dashboard-stats-link" %>
	</div>
</div>

app/views/admins/statistics.html.erb
<div class = "stats-impressions-chart">
	<%= pie_chart Impression.group(:impressionable_id).count, width: "450px", :library => {title: "Page Hits by User"} %>
</div>

<div class = "stats-impressions-chart">
	<%= pie_chart Reply.group(:user).count, width: "380px", :library => {title: "Replies by User"} %>
</div>

<div class = "stats-impressions-chart">
	<%= pie_chart User.group(:last_sign_in_at).count, width: "380px" %>
</div>

<div class = "stats-impressions-chart">
	<%= pie_chart Impression.group(:user_id).count, width: "380px" %>
</div>

app/views/admins/subforums_index.html.erb
<% @subforums.each do |subforum| %>
	<p><%= subforum.title %></p>
	<p><%= subforum.description %></p>
	<%= link_to "Edit", edit_subforum_path(subforum) %>
<% end %>

<%= link_to "New Subforum", new_subforum_path %>

app/views/admins/topics_index.html.erb
<% @topics.each do |topic| %>
	<p><%= topic.title %></p>
	<%= link_to "Edit", edit_topic_path(topic) %>
<% end %>

app/views/admins/users_index.html.erb
<div class = "admin-users-container">
<% @users.each do |user| %>
	<div class = "admin-users-info group">
		<%= image_tag(user.avatar, class: "admin-users-info-avatar") %>
		<p><%= user.username %></p>
		<%= link_to "Edit", edit_user_path(user) %>
		<p>Admin: <%= user.admin? %></p>
	</div>
<% end %>

<%= link_to "New User", new_user_path %>
</div>