config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :users
  get 'profile' => 'profiles#show'

  scope "/admin" do
    resources :users, :controller => "users"
  end
  get 'dashboard' => 'admins#dashboard'
  get 'subforums_index' => 'admins#subforums_index'
  get 'users_index' => 'admins#users_index'
  get 'topics_index' => 'admins#topics_index'
  get 'statistics' => 'admins#statistics'
  
  resources :subforums, shallow: true do
  	resources :topics do
  		resources :replies
  	end
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :subforum
	belongs_to :user
	has_many :replies
	validates :title, presence: true, length: {maximum: 200}
	validates :content, presence: true, length: {maximum: 5000}
	is_impressionable

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	impressionist :actions => [:show]
	before_action :authenticate_user!

	def new
		@subforum = Subforum.find(params[:subforum_id])
		@topic = @subforum.topics.new
	end
	
	def create
		@subforum = Subforum.find(params[:subforum_id])
		@topic = @subforum.topics.new(topic_params)
		@topic.user_id = current_user.id
		if @topic.save
			redirect_to @subforum
		else
			render 'new'
		end
	end
	
	def edit
		@topic = Topic.find(params[:id])
	end
	
	def update
		@topic = Topic.find(params[:id])
		if @topic.update_attributes(topic_params)
			redirect_to @topic
		else
			render 'edit'
		end
	end
	
	def show
		@topic = Topic.find(params[:id])
		@reply = Reply.new
	end

	def destroy
		authorize! :destroy, @topic
		@topic = Topic.find(params[:id]).destroy
		redirect_to root_path
	end
	
	def topic_params
		params.require(:topic).permit(:title, :content)
	end
	
	def set_subforum
		@subforum = Subforum.find(params[:id])
	end

end

app/helpers/topics_helper.rb
module TopicsHelper

   def owned?(subject)
		current_user.id == subject.user_id
	end

end

app/views/topics/_form.html.erb
<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for [@subforum, @topic]  do |f| %>

			<%= f.label :title %>
			<%= f.text_field :title %>
		  
			<%= f.label :content %>
			<%= f.text_field :content %>
		 
			<%= f.submit  "Submit", data: {disable_with: "Creating..."} %>
		  
		<% end %>
	</div>
</div>

app/views/topics/_topic.html.erb
<div class = "topic-page group">
			
	<div class = "topic-page-left group">
		<%= link_to topic.title, topic_path(topic), class: "topic-page-title group" %>
		<p class = "topic-page-description group"><%= topic.created_at%></p>
	</div>
	
	<div class = "topic-page-right group">
		<div class = "topic-page-stats group">
			<p class = "topic-page-threads group"><%= topic.replies.size %> Replies</p>
			<p class = "topic-page-posts group"><%= "#{topic.impressionist_count}" %> Views</p>
		</div>

		<% if topic.replies.size < 1 %>
			<div class = "topic-page-recent-thread-topic group">
				<%= image_tag(topic.user.avatar, class: "topic-page-recent-user group") %>
				<div class = "topic-page-recent-thread-topic-2">				
					<p class = "topic-page-recent-thread-title"><%= topic.user.username %></p>
					<p class = "topic-page-recent-thread group"><%= topic.created_at.strftime("%d %b %Y") %></p>
				</div>				
			</div>
		<% else %>
			<% topic.replies.order("created_at DESC").limit(1).each do |reply| %>
				<div class = "topic-page-recent-thread-topic group">
					<%= image_tag(reply.user.avatar, class: "topic-page-recent-user group") %>
					<div class = "topic-page-recent-thread-topic-2">				
						<p class = "topic-page-recent-thread-title"><%= reply.user.username %></p>
						<p class = "topic-page-recent-thread group"><%= reply.created_at.strftime("%d %b %Y") %></p>
					</div>				
				</div>
			<% end %>
		
		<% end %>
	</div>
	
</div>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<%= render 'form' %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

app/views/topics/show.html.erb
<div class = "topic-show-header">
	<div class = "topic-show-header-left">
		<h1 class = "topic-show-title"><%= @topic.title %></h1>
		<p class = "topic-show-description">Started by <%= @topic.user.username %>, <%= @topic.created_at.strftime("%d %b %Y")%></p>
	</div>
</div>

<div class = "topic-show-posts group">

	<div class = "topic-show-user-header group">
		<p class = "topic-show-user-username"><%= @topic.user.username %></p>

		<div class = "topic-show-user-right">
			<% if can? :destroy, @topic %>
				<p class = "topic-show-reply-number"><%= link_to "Delete Topic", @topic, method: :delete, data: {confirm: "You sure?"} %></p>
			<% end %>
			<p class = "topic-show-reply-number">#1</p>
		</div>
	</div>


	<div class = "topic-show-reply-content group">
		<div class = "topic-show-user-info">
			<%= image_tag(@topic.user.avatar, class: "topic-show-user-avatar") %>
			<p class = "topic-show-user-replies"><%= @topic.user.replies.size %> Posts</p>
		</div>
		<div class = "topic-show-reply-words"><%= @topic.content %></div>
	</div> 
	
</div>


<% @topic.replies.order("created_at ASC").each do |reply| %>
	
		<%= render reply %>
		
	<% end %>


<%= render 'replies/form' %>