config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :users
  get 'profile' => 'profiles#show'

  scope "/admin" do
    resources :users, :controller => "users"
  end
  get 'dashboard' => 'admins#dashboard'
  get 'subforums_index' => 'admins#subforums_index'
  get 'users_index' => 'admins#users_index'
  get 'topics_index' => 'admins#topics_index'
  get 'statistics' => 'admins#statistics'
  
  resources :subforums, shallow: true do
  	resources :topics do
  		resources :replies
  	end
  end

end

app/models/subforum.rb
class Subforum < ActiveRecord::Base
	has_many :topics
	has_many :replies
	validates :title, presence: true, length: {maximum: 20}
	validates :description, presence: true, length: {maximum: 65}

	SUBHEADINGS = ["Main", "Secondary", "Miscellaneous"]




end

app/controllers/subforums_controller.rb
class SubforumsController < ApplicationController

	load_and_authorize_resource
	skip_authorize_resource :only => :show

	def new
		@subforum = Subforum.new
	end
	
	def create
		@subforum = Subforum.new(subforum_params)
		if @subforum.save
			redirect_to root_url
		else
			render 'new'
		end
	end
	
	def edit
		@subforum = Subforum.find(params[:id])
	end
	
	def update
		@subforum = Subforum.find(params[:id])
		if @subforum.update_attributes(subforum_params)
			redirect_to root_path
		else
			render 'edit'
		end
	end
	
	def show
		@subforum = Subforum.find(params[:id])
	end
	
	def destroy
		@subforum = Subforum.find(params[:id]).destroy
	end
	
	def subforum_params
		params.require(:subforum).permit(:title, :description, :subheading)
	end

end

app/helpers/subforums_helper.rb
module SubforumsHelper

	def self.subforum_big?
		return true if self 
	end


end

app/views/subforums/_form.html.erb
<div>
	<div>
		<%= form_for(@subforum) do |f| %>

			<%= f.label :title %>
			<%= f.text_field :title %>
		  
			<%= f.label :description %>
			<%= f.text_field :description %>

			<%= f.label :subheading %>
			<%= f.select :subheading, options_for_select(Subforum::SUBHEADINGS, @subforum.subheading) %>
		 
		 	<% if current_page?(controller: 'subforums', action: 'new') %>
				<%= f.submit  "Create Subforum", data: {disable_with: "Creating..."} %> 
			<% else current_page?(controller: 'subforums', action: 'edit') %>
				<%= f.submit  "Edit Subforum",  data: {disable_with: "Updating..."} %>
			<% end %>
		  
		<% end %>
	</div>
</div>

app/views/subforums/_subforum.html.erb
<div class = "page-section">
			
	<div class = "page-section-left">
		<%= link_to subforum.title, subforum_path(subforum), class: "page-section-title" %>
		<p class = "page-section-description"><%= subforum.description %></p>
	</div>
	
	<div class = "page-section-right">
	
		<div class = "page-section-stats">
			<p class = "page-section-threads"><%= subforum.topics.size %> Topics</p>
			<p class = "page-section-posts"><%= subforum.replies.size %> Replies</p>
		</div>
		
		<% subforum.topics.order("created_at DESC").limit(1).each do |topic| %>
			<div class = "page-section-recent-thread-section">
				<%= image_tag(topic.user.avatar, class: "page-section-recent-user") %>
				<div class = "page-section-recent-thread-section-2">
					<% if topic.title.size > 30 %>
						<p class = "page-section-recent-thread-title"><%= topic.title[0..25] %>...</p>
					<% else %>				
						<p class = "page-section-recent-thread-title"><%= topic.title %></p>
					<% end %>
						<p class = "page-section-recent-thread"><%= topic.user.username %></p>
				</div>
			</div>
		<% end %>
				
			
	</div>
	
</div>
			

app/views/subforums/edit.html.erb
<h1>Edit Subforum</h1>

<%= render 'form' %>

app/views/subforums/new.html.erb
<h1>New Subforum</h1>

<%= render 'form' %>

app/views/subforums/show.html.erb
<div class = "subforum-show-header">
	<div class = "subforum-show-header-left">
		<h1 class = "subforum-show-title"><%= @subforum.title %></h1>
		<p class = "subforum-show-description"><%= @subforum.description %></p>
	</div>
	<div class = "subforum-show-header-right">
		<p class = "subforum-show-newtopic"><%= link_to "Create a Topic", new_subforum_topic_path(@subforum) %></p>
	</div>
</div>

<% @subforum.topics.paginate(:per_page => 30, :page => params[:page]).order("created_at DESC").each do |topic| %>
	<%= render topic %>
<% end %>