config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :users
  get 'profile' => 'profiles#show'

  scope "/admin" do
    resources :users, :controller => "users"
  end
  get 'dashboard' => 'admins#dashboard'
  get 'subforums_index' => 'admins#subforums_index'
  get 'users_index' => 'admins#users_index'
  get 'topics_index' => 'admins#topics_index'
  get 'statistics' => 'admins#statistics'
  
  resources :subforums, shallow: true do
  	resources :topics do
  		resources :replies
  	end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForumApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header class = "header">
		
		<div  class = "header-left">
			<%= image_tag("home.png", class: "header-home-icon") %>
			<%= link_to "Home", root_path, class: "header-home-link" %>
		</div>
		
		<% if user_signed_in? %>
			<div class = "header-logged-in" >
				<% if current_user.admin? %>
					<p class = "header-username"><%= link_to "Dashboard", dashboard_path %></p>
				<% end %>
				<%= link_to(profile_path) do %>
					<%= image_tag(current_user.avatar, class: "header-profile-pic") %>
					<p class = "header-username"><%= current_user.username %></p>
				<% end %>
				<%= link_to "Logout", destroy_user_session_path, :method => :delete, class: "header-logout" %>
			</div>
		<% else %>
			<div class = "header-logged-out">
				<%= image_tag('key.png', class: "header-signin-logo" ) %>
				<%= link_to "Sign In", new_user_session_path, class: "header-sign-in" %>
				<%= image_tag('register.png', class: "header-register-logo" ) %>
				<%= link_to "Register", new_user_registration_path, class: "header-register" %>
			</div>
		<% end %>
		
	</header>
	
	<div class = "hero">
	
		<nav class = "hero-nav">
			<%= link_to "Community", '#', class: "hero-nav-link" %>
			<%= link_to "Guides", '#', class: "hero-nav-link" %>
			<%= link_to "Shop", '#', class: "hero-nav-link" %>
			<%= link_to "Help", '#', class: "hero-nav-link" %>
		</nav>
	
	</div>
	
	<div class = "main-wrapper group">

		<%= yield %>

	</div>

</body>
</html>